# Generated by Django 6.0.1 on 2026-04-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
